### ISSUE TITLE
PHP Ver 5.5

### ISSUE THREAD

**Issue by ttv-voidgg** [alemohamad/ci-steam-api#2]
$this->steamapi->getPlayerSummary()
Does not work on php 5.5

**Comment by alemohamad-mobomo** [comment]
This is a very old project (almost abandoned).
You can fork it and try to make it work. I think that the API is an old one, and that's why it's not currently working.

**Comment by alemohamad** [comment]
This is a very old project (almost abandoned).
You can fork it and try to make it work. I think that the API is an old one, and that's why it's not currently working.
